apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: admin
spec:
  rules:
    - host: app.admin.com
      http:
        paths:
          - backend:
              serviceName: admin-service
              servicePort: 3000
