apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: manager
spec:
  rules:
    - host: app.manager.com
      http:
        paths:
          - backend:
              serviceName: manager-service
              servicePort: 5000
