apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-vs
spec:
  hosts:
    - 'app.admin.com'
  gateways:
    - isto-gateway
  http:
    - route:
        - destination:
            host: admin.default.svc.cluster.local
            port:
              number: 3000
