apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: crkushal7/auth:2.0.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '200m'
            requests:
              cpu: '100m'
          ports:
            - containerPort: 4000
              protocol: TCP
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth
                  key: PORT
            - name: NAME
              valueFrom:
                configMapKeyRef:
                  name: auth
                  key: NAME
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: auth
                  key: HOST
            - name: ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: auth
                  key: ADMIN_URL
            - name: MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: auth
                  key: MANAGER_URL
