apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  labels:
    app: minio
spec:
  storageClassName: minio-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
