name: Packages - ui & common

on:
  push:
    branches:
      - dev
      - master

defaults:
  run:
    working-directory: "./"

jobs:
  Build:
    runs-on: ubuntu-latest

    if: ${{ !contains(github.event.head_commit.message, 'skip ci') && github.event_name == 'push' && github.ref == 'refs/heads/dev'}}

  steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Publish new release
      run: release.sh
