name: Packages - ui & common

on:
  push:
    branches:
      - dev
      - master

defaults:
  run:
    working-directory: "./"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup git
        run: |
          git config --global user.name "Kushal"
          git config --global user.email "kushal@gmail.com"

      - name: Build docker images
        run: |
          ./build.sh
