name: Packages - ui & common

on:
  push:
    branches:
      - dev
      - master

defaults:
  run:
    working-directory: "./"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup semver bash
        run: |
          sudo curl https://raw.githubusercontent.com/fsaintjacques/semver-tool/2.1.0/src/semver -o /usr/local/bin/semversion && sudo chmod +x /usr/local/bin/semversion
          semversion --version

      - name: Setup hub
        run: |
          sudo snap install hub --classic
          hub --version

      - name: Setup git
        run: |
          git config --global user.name "Kushal"
          git config --global user.email "kushal@gmail.com"

      - name: Build docker images
        run: |
          ./build.sh
